### PR TITLE
Hot Reloading

### PR DESCRIPTION
**Pull request by AdrianoAE**
Hello, before anything thank you very mutch for this project.

This PR enables Hot Reloading, Only did a little change in the original code to allow loading the assemblies in memory.
```
public Assembly LoadDefaultAssembly()
{
    EnsureNotDisposed();
#if FEATURE_UNLOAD
    if (_context.IsCollectible)
    {
        using (var fs = new FileStream(_config.MainAssemblyPath, FileMode.Open, FileAccess.Read))
        {
            return _context.LoadFromStream(fs);
        }
    }
#endif
    return _context.LoadFromAssemblyPath(_config.MainAssemblyPath);
}
```
After that I created a wrapper to take care of everything in the plugin folder. It will be watching the folder and reload/unload everything that changed.

usage (full test code: https://github.com/AdrianoAE/DynamicLoadingAspNetCore)
```
private readonly HotReloadManager<IPaymentMethod> _paymentMethods;
 IReadOnlyDictionary<string, IPaymentMethod> IPayments.PaymentMethods => _paymentMethods.Plugins;

public Payments()
{
    _paymentMethods = HotReloadManager<IPaymentMethod>.InitializeBasePath("Plugins");
     //_paymentMethods = HotReloadManager<IPaymentMethod>.InitializeFullPath(@"...PATH...\Plugins\");
}
```
There are things missing, like implemeting it as extension for the MVC, in case files are renamed and other things that I missed for sure.

Atm I'm throwing when the assembly could not unload wouldn't it be better to have a event on failled?

### CODE REVIEW

**Comment by zHaytam** [comment]
Nice! I would've implemented it the same way I believe. I have some questions tho:
 - Why are you loading the non-unloadable assemblies in memory?
 - Why doesn't the `HotReloadManager` have events when a plugin is loaded/unloaded? For the use cases I can think of, knowing that the plugins changed is good so that I act on it.

**Comment by AdrianoAE** [comment]
@zHaytam it only loads the assemblies in memory if _context.IsCollectible is true (which in case of HotReloadManager will always be true).

I've been working on this manager and a few things have already changed. (I'll release those updates at the weekend)
Renamed from HotReloadManager to ModuleManager
Added a class ModuleManagerConfiguration (to configure how the modules should be loaded)

Features added already:
• Configure if the manager instance should load the assemblies as hotreload or normal (locking them)
• Passing parameters to the modules
(Modules = Class Instance)
- If assembly1 have class A and B (and both implements the Interface asked in the manager) A and B are considered modules.
• Enable/Disable Modules at runtime. Why? I'm working on a project that the modules can be configured in a database, so for example I can say in the database that module A isActive and module B isn't.
    • Two ways it works atm:
         • At startup I can give to the manager a list of the module names that I don't want to be active (they will be loaded but will be placed in a different and can be activated/deactivated at runtime (using managerInstance.ActivateModule(name);
         • After startup, define if we want all the new assemblies loaded to be loaded as inactive (a event is fired) so we can decide if we want to turn it on or not based by whatever conditions.

I'll try to publish those updates before sunday.

**Comment by natemcmaster** [comment]
@AdrianoAE first of all, thanks for starting work on this. If we can get hot reloading working well, this will be a super addition to the library. 

I have a few concerns about this implementation. My concerns about the design of this approach fall into two primary categories:
1. API usage - as someone just reading the API for the first time, it's not obvious to me how `HotReloadManager<T>` is supposed to be used. I'd like to draft some alternative usages to see if we can find something that makes it trivial to configure a plugin for hot reloading.
2. Fundamental lack of support for this in .NET Core. This is a deliberate attempt to workaround a fundamental problem in .NET Core, which is that .dll files are locked once they are loaded into memory. This issue has been raised several times before to the ASP.NET Core team (cref https://github.com/aspnet/AspNetCore/issues/3793, https://github.com/aspnet/AspNetCore/issues/3719). I couldn't find a better issue for this in dotnet/coreclr or corefx. I think it's worth communicating with the .NET team about this. .NET Framework had a feature called "shadow copy" which was created to workaround this problem. It was typically only used for ASP.NET 4 and IIS scenarios. No such feature exists in .NET Core. The only workaround I'm aware of is the one you've started to implement: using `LoadFromStream`. This has some perf problems, and also slightly changes the behavior of an assembly, for example, the values of `Assembly.Location` and `Assembly.CodeBase`: https://github.com/dotnet/coreclr/issues/25002. Let's test the impact of this workaround in terms of perf and functionality on some broader scenarios to make sure it works.

I also have some feedback on the code. A few changes are going to be necessary (for example, use `Path.Combine` to ensure file paths are compatible with Linux), but since you are already working on more updates, I will reserve those comments until after you finish your next round of updates.

Thanks for getting this started! I'm looking forward to polishing this up a bit more and getting this into a beta release for others to try!

-Nate

**Comment by AdrianoAE** [comment]
A small review on the changes:
• The ModuleManager (old HotReloadManager) can now be used even when the unload feature isn't availabe.

Usage (I'll release the example I'm working with later today or tomorrow):
```
var config = new ModuleManagerConfiguration
{
    Path = path,
    HotReload = true,
    OnLoadSetInactive = true,
    ModulesToLoadAtStartup = activeMethods
};
var providers = new ModuleManager<IProvider>(config, connectionString);
```
Or
```
var providers = FluentModuleManager<IProvider>.WithPath(path)
    .WithModuleParameters(connectionString)
    .EnableHotReload()
    .EnableOnLoadSetInactive()
    .SetModulesToLoadAtStartup(activeMethods)
    .Complete();
```

**Comment by AdrianoAE** [comment]
Hello @natemcmaster, thank you very mutch for your feedback.

• Yes I agree that I went to a very specific scenario (they are the requirements I have) and I totally agree that it's not suitable as a abstract thing that can be used in multiple scenarios. 
• I didn't knew about the System.Reflection.Module.
• I haven't tested anything with depedencies, but will have a look into that depending on the feedback in the #37 .
• I've never worked on systems like that with plugins, so I don't have mutch knowledge on what people are expecting or what are the common usages and methodologies used to develop them.

I'll keep working and improving based on your feedback and the ones in the discussion. Hope we can make something that works well for everyone.

**Pull request closed without merging**
