### PR TITLE
Web Plugin Examples

### PR DESCRIPTION
**Pull request by keggyy**
**Feature**
This commit contains fourth scenario of web plugin loading implementation. The example has this structure:

- WebHost reference Library that has a common interface called for configure IServiceCollection
- Two library project (PluginLib that contains interface and PluginLib that contains the implementation of PluginLib) loaded with your solution
- On the fourth scenario load PluginImplOverride project for override a runtime Plugin implementation

These scenarios can be useful for delegate functional implementation without necessarily knowing host structure or write a different implementation of the same plugin

**Problem**
Only Third scenario seems to work (you can show startup class for all scenario implementation), for others when call /api/fruit controller DI is unable to resolve service ad I get this error 
`System.InvalidOperationException: Unable to resolve service for type 'PluginLib.Classes.IFruitService' while attempting to activate 'PluginLib.FruitController'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound) .......`

I have shown that IServiceProvider in this context doesn't have any registration and in AppDomain we have loaded many times PluginLib Assembly (is not shared !!), all work fine if you move to interface implementation inside the library plugin.
I think that for some reason PluginLib, when loaded, is not shared between Plugin, can you help me to find the error on implementation and understand if the fourth scenario is possible?  
Many thanks

### CODE REVIEW

**Comment by natemcmaster** [comment]
Hey @keggyy, thanks for sending your first pull request to this repo! I'm happy to have a new contributor. 

I don't plan to accept this pull request yet. Before we spend time working on improving the code quality, let's see if we can clarify first what this sample will be demonstrating. Based on this first draft, I'm not sure you really wanted to show that isn't already in [samples/dynamic-implementation/](https://github.com/natemcmaster/DotNetCorePlugins/tree/master/samples/dynamic-implementation). I have a guess, but I could be wrong, so would you mind telling me? I think the first/second/third/fourth scenario code is what is confusing me.

Once we get that straightened out, we can proceed to cleaning up the code...but let's hold off on that separate discussion until the "theme" of this sample is clear.

> I think that for some reason PluginLib, when loaded, is not shared between Plugin,

Yes, that is the case. This is why the sample in [samples/dynamic-implementation/](https://github.com/natemcmaster/DotNetCorePlugins/tree/master/samples/dynamic-implementation) places `IFruitService` in a "Contracts" library which is shared by the host and all plugins. Your sample puts `IFruitService` in a plugin only and isn't loaded by the host, so this type won't be shared between plugins. See https://github.com/natemcmaster/DotNetCorePlugins/issues/60 for a more detailed discussion on this behavior.

Thanks,
Nate

**Comment by keggyy** [comment]
Hi @natemcmaster,
thank you so much for your quick review and your directions.
Sorry if I don't be cleared on the previous commit but I have found a solution for my final scope only now and try to explain to you (I have removed all scenario and refactor only last).

In this example, I would like to show how using your solution mixed DI you can implement a version of the contract plugin and if necessary you can override/extend this implementation with another plugin without the two implementations are related.

Web-Plugin

I would like to use this solution on our opensource project [RawCMS](https://github.com/arduosoft/RawCMS) where use plugins for loading capability. In this example try to demonstrate that our team can develop capability but finals users can override/extend without a particular problem, the only requirement is to have a direct reference to contract plugin.

Please tell me if now is more clear and if you see problems with this solution
Thanks
Emanuele

**Comment by natemcmaster** [comment]
Thanks for explaining more. Based on what you've said, I only see one significant difference between the content of this pull request and the existing [dynamic-implementation sample](https://github.com/natemcmaster/DotNetCorePlugins/tree/master/samples/dynamic-implementation): the usage of ASP.NET Core. If that remains the only difference, I would prefer to keep just one sample. 

That said, did you find it challenging to use the existing sample (which is just a console app) to guide your efforts to build an ASP.NET Core app? 

I could be convinced that the dynamic-implementation sample needs to be augmented, but I'm not yet convinced that we need an entirely new sample. But please, correct me if I'm missed some important differences between what you've written so far.

**Comment by keggyy** [comment]
Hi @natemcmaster,
in addition to use ASP.NET core, the main difference with dynamic-implementation sample is the use of abstract plugin shared with Host and other plugins. This little difference was the motive of my first PR where three scenarios not working on how aspect but thanks to your suggestions I understand that shared plugin cant' loaded with plugin loader (precisely because of the context ar isolated).
Apart from this, the two examples are very similar.
I close this PR and I hope to work a new feature on the future of this fantastic library.
Many thanks

**Comment by natemcmaster** [comment]
Ok, I hope this conversation was helpful. Thanks @keggyy !

**Pull request closed without merging**
